#!/bin/bash

CUDA_HOME=/usr/local/cuda
ln -s /usr/local/cuda/lib64/libcurand.so.10.0 /usr/local/cuda/lib64/libcurand.so.10
mkdir -p externals && cd externals

if [ ! -d warp-transducer ]; then
    git clone https://github.com/usimarit/warp-transducer.git
    
cd ./warp-transducer
mkdir -p build && cd build
cmake \
-DUSE_NAIVE_KERNEL=on \
-DCMAKE_C_COMPILER_LAUNCHER="$(which gcc)" \
-DCMAKE_CXX_COMPILER_LAUNCHER="$(which g++)"  \
-DCUDA_TOOLKIT_ROOT_DIR="$CUDA_HOME" ..

make
cd ../tensorflow_binding
CUDA="$CUDA_HOME" python3 setup.py install --user

wget -qO-  https://raw.githubusercontent.com/usimarit/warp-transducer/master/tensorflow_binding/tests/test_basic.py | python3 -