config = {
    'embedding_hidden_size': 512,
    'initializer_range': 0.02,
    'embedding_dropout_prob': 0.1,
    'n_speakers': 1,
    'n_conv_encoder': 5,
    'encoder_conv_filters': 512,
    'encoder_conv_kernel_sizes': 5,
    'encoder_conv_activation': 'relu',
    'encoder_conv_dropout_rate': 0.5,
    'encoder_lstm_units': 256,
    'n_prenet_layers': 2,
    'prenet_units': 256,
    'prenet_activation': 'relu',
    'prenet_dropout_rate': 0.5,
    'n_lstm_decoder': 1,
    'reduction_factor': 1,
    'decoder_lstm_units': 1024,
    'attention_dim': 128,
    'attention_filters': 32,
    'attention_kernel': 31,
    'n_mels': 80,
    'n_conv_postnet': 5,
    'postnet_conv_filters': 512,
    'postnet_conv_kernel_sizes': 5,
    'postnet_dropout_rate': 0.1,
    'attention_type': 'lsa',
}
