WANDB_PROJECT=malaysian-distilled-whisper-2 \
torchrun --nproc_per_node 4 \
-m distill \
--model_name_or_path "./distil-large-v3-init" \
--teacher_model_name_or_path "openai/whisper-large-v3" \
--train_dataset_name "mosaic-stt" \
--save_steps 300 \
--warmup_steps 100 \
--learning_rate 0.0001 \
--dtype "bfloat16" \
--lr_scheduler_type "constant_with_warmup" \
--logging_steps 1 \
--save_total_limit 3 \
--num_train_epochs 3 \
--per_device_train_batch_size 24 \
--output_dir "./distil-large-v3-2" \
--do_train \
--gradient_checkpointing \
--freeze_embed_positions \
--freeze_encoder \
--max_label_length 440 \
--wandb_project "malaysian-distilled-whisper"