WANDB_PROJECT=malaysian-whisper-medium-v3 \
~/.local/bin/torchrun --nproc_per_node 4 \
-m whisper \
--model_name_or_path "openai/whisper-medium" \
--train_dataset_name "mosaic-stt" \
--eval_steps 1000 \
--save_steps 100 \
--warmup_steps 100 \
--learning_rate 0.00005 \
--lr_scheduler_type "constant_with_warmup" \
--logging_steps 1 \
--save_total_limit 3 \
--num_train_epochs 3 \
--per_device_train_batch_size 128 \
--per_device_eval_batch_size 4 \
--output_dir "./medium" \
--do_train \
--gradient_checkpointing \
--predict_with_generate \
--max_label_length 440 \
--bf16